//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Auction = new HashSet<Auction>();
            this.OnSaleProducts = new HashSet<OnSaleProducts>();
            this.ProductCommentary = new HashSet<ProductCommentary>();
            this.ProductsSold = new HashSet<ProductsSold>();
            this.Category = new HashSet<Category>();
        }

        [Required(ErrorMessage = "Please provide a product name.", AllowEmptyStrings = false)]
        [MaxLength(60, ErrorMessage = "Product name can not be longer than 60 characters.")]
        [DisplayName("Product Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please provide a product price", AllowEmptyStrings = false)]
        [Range(0, int.MaxValue, ErrorMessage = "The product can not be so expensive")]
        [DisplayName("Price")]
        public Nullable<int> Price { get; set; }
        public int UserID { get; set; }
        public int ShippingID { get; set; }
        [MaxLength(123, ErrorMessage = "The product description can not be longer than 123 characters.")]
        [DisplayName("Description")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please provide the Quantity value", AllowEmptyStrings = false)]
        [DisplayName("Quantity")]
        public Nullable<int> Existencies { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> isAuction { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnSaleProducts> OnSaleProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCommentary> ProductCommentary { get; set; }
        public virtual ImageCatalog ImageCatalog { get; set; }
        public virtual ShippingOptions ShippingOptions { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsSold> ProductsSold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
    }
}
